#JANELA
TITLE = "Placeholder name"
LARGURA = 1550
ALTURA = 900
FPS = 60

#PLAYER
PLAYER_X_INICIAL = LARGURA / 2
PLAYER_Y_INICIAL = 800
PLAYER_RAIO = 20
PLAYER_SPEED = 800
PLAYER_SPEED_VERTICAL = 250
PLAYER_SPEED_RASTRO = 500
PLAYER_TAMANHO_RASTRO = 30

#PLAYER - BOOST (bounce)
PLAYER_BOOST_FATOR = 3       # multiplicador de velocidade durante o boost
PLAYER_BOOST_DURACAO = 0.4   # segundos

#OBSTACULOS
OBSTACLE_RAIO = 120
OBSTACLE_VELOCIDADE = 600

#ENEMY
ENEMY_SPEED = 400
ENEMY_RAIO = 14
ENEMY_SPAWN_INTERVALO = 2.0
ENEMY_MAX = 20
ENEMY_SPAWN_Y = -30

#HUD
FONTE_UI = "Arial"
FONTE_TEXTO = 36
FONTE_SCORE = FONTE_TEXTO + 4

#MENU
FONTE_TITULO = 72
FONTE_MENU = 28

#PROJECTILES (TIRO)
PROJECTILE_SPEED = 1500
PROJECTILE_RAIO = 8
PROJECTILE_COOLDOWN = 0.0  # tempo mínimo entre tiros (segundos)

#SCORE
SCORE_POR_SEGUNDO = 1
SCORE_INIMIGO_DESTRUIDO = 1
SCORE_COLETA = 5
NIVEL_INTERVALO = 10
NIVEL_MAX = 10

#DIFICULDADE
DIFFICULTY_LIMIT = 1
DIFFICULTY_SLOPE = 0.004
DIFFICULTY_MIDPOINT = 2000
DIFFICULTY_ENEMY_SPEED_FACTOR = 1.0
DIFFICULTY_SPAWN_FACTOR = 0.8
DIFFICULTY_SCROLL_FACTOR = 0.6

#CORES
COR_FUNDO = "#212040"
COR_TEXTO = (255, 255, 255)
COR_PINK = "pink"
COR_RED = "red"
COR_BLUE = "blue"
COR_PLAYER_BOOST = (255, 220, 0)

#OBSTACULOS - MORTAL / BOUNCE (spawn em ondas)
RAIO_MORTAL = 180
RAIO_BOUNCE = 90

VEL_MIN = 420
VEL_MAX = 620

# Intervalo entre ondas de spawn (segundos)
INTERVALO_SPAWN = 2.2

# Quantos obstáculos por onda
QTDE_POR_ONDA = 3

# Distância horizontal mínima entre os CENTROS de dois obstáculos da mesma onda.
# Evita que eles nasçam colados/sobrepostos mesmo com jitter.
DISTANCIA_MIN_X = (RAIO_MORTAL * 2) + 60

# Margem vertical fora da tela onde o obstáculo nasce
MARGEM_SPAWN_Y = -80

# Espaçamento vertical extra entre obstáculos da MESMA onda
# (cada obstáculo subsequente nasce mais "atrasado" verticalmente)
ESPACAMENTO_VERTICAL_MIN = 250
ESPACAMENTO_VERTICAL_MAX = 450